### ISSUE TITLE
GPU Mining

### ISSUE THREAD

**Issue by xloem** [datacoinproject/datacoin#7]
It's so great to see so much activity on this project.  I haven't had time to get involved again myself.

Some time ago I was concerned to see that the mining server was removed from the source.  Before it was removed, I had rigged the code up locally to a gpu miner to quickly get myself some datacoins for testing.  ([old branch](https://github.com/xloem/datacoin/tree/still-provides-for-external-miner) i think it might no longer build after trying to rebase onto newer changes)

It could endanger the chain to have everybody cpu-mining when a gpu-mining interface was available in the past.

Is there an avenue for GPU accelerated mining nowadays?

**Comment by gjhiggins** [comment]
Sorry for the late response, I'd failed to update my watch settings to include All Activity.

“_I was concerned to see that the mining server was removed from the source._” That was my call, based on an ease-of-maintenance assessment - i.e. I wouldn't be able to provide support should it prove problematic. CrossVerse is no longer around to explain why the madpool server was included in the first place, the in-wallet miner works just fine without it and so does xpmclient. So, seeing as it introduced additional dependencies, was buggy and the protobuf stuff was forever posing a build problem, I couldn't see any justification for retaining someone else's unmaintained/abandoned code. I don't think it'd be too taxing to re-include in an alternative Datacin client.

With respect to GPU-accelerated mining, there are still Windows and Linux xpmclient XPM-but-usable-with-DTC GPU binaries available from URLs listed in eXtremal-ik7's [bitcointalk thread](https://bitcointalk.org/index.php?topic=831708), both [CUDA](https://bitcointalk.org/index.php?topic=831708.msg56465643#msg56465643) and [OpenCL](https://bitcointalk.org/index.php?topic=831708.msg57002698#msg57002698) - the CUDA xpmclient binary works off the bat on my Dell XPS nVidia GPU with just changing the config.txt settings to use the graymines URL and a Datacoin address.

And, although the released Linux binary didn't work for me, the Primecoin github repos as has clones of eXtremal’s [xpmminer](https://github.com/primecoin/xpmminer) and [xpmclient](https://github.com/primecoin/xpmclient), both of which are showing recent development activity and which might well be adapted for use with Datacoin.

**Comment by xloem** [comment]
Thanks.  I haven't tried the solutions you mention but it's great to know there are so many.
